### ISSUE TITLE
Transfer taskstemplates, organizations and infocards from strapi to yaml + connect to transifex

### ISSUE THREAD

**Issue by noamoss** [hasadna/reportit-scripts#4]

**Comment by akariv** [comment]
All datasets are now served from github and not from strapi.

@oferb needs to implement an endpoint that serves the data in a similar way as these files:
https://github.com/hasadna/reportit-scripts/blob/master/src/datasets/infocards.datapackage.json
https://github.com/hasadna/reportit-scripts/blob/master/src/datasets/organizations.datapackage.json
https://github.com/hasadna/reportit-scripts/blob/master/src/datasets/tasktemplates.datapackage.json

These files are also being translated in transifex now. rebuild in travis to redeploy translations, as usual, so same 'publish' button can be used to redeploy this as well.

**Comment by noamoss** [comment]
@akariv  not sure what is the current status though. Please explain before I break anything - mainly - can/should I update scripts and deploy, or everything will collapse on the live version as long as @oferb won't implement his side?

In other words, is there an option to perform QA here?

**Comment by noamoss** [comment]
@akariv finished moving all content to the yaml, opened a followup: https://github.com/hasadna/reportit-agent/issues/69

**Comment by akariv** [comment]
@noamoss I now connected to transifex - some fields might need to be re-translated (as field names changed)

**Comment by akariv** [comment]
I now need to update the agent to work with these modified field names...

**Comment by noamoss** [comment]
@akariv 

>I now need to update the agent to work with these modified field names...

so this is a coding task? if so, I am assigning back to you. If not, please explain.

**Comment by akariv** [comment]
Coding & translation in transifex

**Comment by akariv** [comment]
Thus is should remain assigned to both of us

**Comment by noamoss** [comment]
@akariv see no point investing time/effort translating this material, as it is for the agent side anyhow - and currently, we can assume agents to be reading and working with the Hebrew interface. 

Please reassign me if you think otherwise.
